### ISSUE TITLE
BigKaka 9.3 Release

### ISSUE THREAD

**Issue by Alaric323** [Ay-De/Surface_Duo_2_GCam#1]
Hey Ay-De, just letting you know you can update your Readme mentioning portrait and photo sphere are broken.  A new AGC 8.4 release fixed both freezing issues.

Your profiles seem to be functioning normally after the update as well.

**Comment by Ay-De** [comment]
Hi sorry for the late reply, i forgot to answer.

Yes i did an update to the Github repo. AGC v9.5 Fix works fine, but going forward i am probably only focusing on the LMC GCam Port. I did a new config for LMC which fixes the green shadows in HDR+Enhanced mode. Otherwise, i didn't change much in the initial config, only some slight denoising.
